###############################################################################
#                          Build by Shadel                                    #
###############################################################################
version: "3.1"
volumes:
  node_modules:
services:

    node:
      image: trieuvo/nodevm:node
      container_name: ng6-angular-node
      working_dir: /application
      volumes:
        - .:/application
        - node_modules:/application/node_modules
      ports:
        - 8080:8080
      tty: true
